from typing import Callable, Any, List, Dict


def mage_counter() -> Callable:
    """
    Create a counting closure that maintains a persistent state.

    This function initializes a counter in its local scope and returns a
    nested function. Because the nested function references the 'counter'
    variable, Python creates a closure, allowing the counter to persist
    on the heap even after 'mage_counter' has finished execution.

    Returns:
        Callable: A function that, when called, increments and
                           returns the current count.
    """

    # Counter to use as a __closure__
    counter: int = 0

    def call_counting() -> int:
        """
        Increment the enclosed counter and return its new value.

        Uses the 'nonlocal' keyword to rebind the 'counter' variable
        defined in the enclosing scope. This prevents Python from
        treating 'counter' as a local variable during assignment.

        Returns:
            int: The current count, starting from 1 on the first call.
        """

        # Using nonlocal since we modifying the value
        # not just using it from the outer, so normally
        # python will assume that its has a local variable
        # not just like using it that why we flag it as nonlocal.
        # for safety and avoid accidentally changing for big code.
        nonlocal counter
        counter += 1

        return counter

    return call_counting


def spell_accumulator(initial_power: int) -> Callable:
    """
    Initialize a stateful power accumulator closure.

    Creates an enclosing scope where the 'power' variable is stored in a cell
    on the heap. This allows the returned 'accumulator' function to access
    and modify the power level across multiple independent calls.

    Args:
        initial_power (int): The starting value for the power accumulation.

    Returns:
        Callable[[int], int]: A function that accepts an integer to add to the
                               total power and returns the updated total.
    """

    # Initial power start.
    power: int = initial_power

    def accumulator(power_amount: int) -> int:
        """
        Add a specified amount to the enclosed power level.

        This function uses the 'nonlocal' declaration to rebind the 'power'
        variable in the enclosing scope. It updates the value stored in the
        closure's cell and returns the new cumulative total.

        Args:
            power_amount (int): The amount of power to add to the current total

        Returns:
            int: The updated total power after the addition
        """

        # Flag the power variable as not local
        nonlocal power

        # Just a safety check if something like power was None.
        try:
            power += power_amount

        except Exception as e:
            print(f"During accumulation: {e}")

        return power

    return accumulator


def enchantment_factory(enchantment_type: str) -> Callable:
    """
    Generate a specialized enchantment function for a specific magic type.

    This is a factory function that uses a closure to capture the
    'enchantment_type' string. Every function generated by this factory
    will "remember" its specific enchantment even after the factory
    function has returned.

    Args:
        enchantment_type (str): The type of magic to bind to the
                                returned function ("Flaming", "Frozen", ...).

    Returns:
        Callable[[str], str]: A function that takes an item name and returns
                              an enchanted description string.
    """

    def enchanting(item_name: str) -> Union[str, None]:
        """
        Apply the pre-set enchantment to a specific item.

        This function performs a read-only access on the 'enchantment_type'
        variable stored in its enclosing scope's cell object.

        Args:
            item_name (str): The name of the item to be enchanted (ex. "Sword").

        Returns:
            str: The formatted string "enchantment_type item_name".
        """
        if not item_name:
            print("Error: During enchanting")
            return None

        # We don't need 'nonlocal' here because we are only reading the value,
        # not trying to rebind the name to a new object.
        return f"{enchantment_type} {item_name}"

    return enchanting


def memory_vault() -> dict[str, Callable]:
    """
    Create a private memory management system using closures.

    This factory function initializes a dictionary on the heap that remains
    accessible only to the 'store' and 'recall' functions. This effectively
    emulates 'private' variables in object-oriented programming.

    Returns:
        dict[str, Callable]: A dictionary containing two methods:
                             'store' and 'recall'.
    """

    # Private dictionary held in the enclosing scope (the "Cell")
    memory: dict[str, Any] = {}

    def store(key: str, value: Any) -> None:
        """
        Store a value in the private memory.

        Note: 'nonlocal' is not strictly required here because we are
        mutating the dictionary via .update(), not reassigning the
        variable name 'memory' itself.
        """
        try:
            memory.update({key: value})
        except Exception as e:
            print(f"During storing memory: {e}")

    def recall(key: str) -> Any:
        """
        Retrieve a value from the private memory by its key.

        Args:
            key (str): The identifier for the stored memory.

        Returns:
            Any: The stored value or the string "Memory not found".
        """
        return memory.get(key, "Memory not found")

    return {"store": store, "recall": recall}


def main() -> None:
    """Main entry point to demonstrate tests"""

    # ----- Counter -----
    print("\nTesting mage counter...\n")

    # Extract the counter function
    counter_fn: Callable = mage_counter()
    for i in range(3):
        print(f"Call {i}: {counter_fn()}")

    # ----- Accumulator -----
    print("\nTesting spell accumulator...\n")

    initial_power: int = 5
    accumulator: Callable = spell_accumulator(initial_power)

    # Print the initial value and the accumulated
    # value after each function call.
    print(f"Initial power: {initial_power}")
    power_additions: List[int] = [12, 13, 7, 19, 17]
    for amount in power_additions:
        print(f"Power: {accumulator(amount)}")

    # ----- Enchantment -----
    print("\nTesting enchantment factory...\n")

    enchantment_types: List[str] = ["Frozen", "Dark", "Flowing"]
    items_to_enchant = ["Ring", "Wand", "Cloak", "Shield"]

    # Enchant each item by all enchantment_types.
    for ench_type in enchantment_types:
        enchanting_fn: Callable = enchantment_factory(ench_type)
        for item in items_to_enchant:
            print(enchanting_fn(item))
        print("")

    # ----- Memory valut -----
    print("\nTesting Memory vault...\n")
    shared_vault: Dict[str, Callable] = memory_vault()

    # Use lambda just to silent the type hint for callable
    store: Callable[[str, Any], None] = shared_vault.get('store', lambda: None)
    recall: Callable[[str], Any] = shared_vault.get('recall', lambda: None)

    # Store  the data in the Cell object
    store("name", "Hakona Matata")
    store("power", 900)
    store("status", "Legendary")

    # Call data even the outer is disappear
    print(recall("name"))
    print(recall("power"))
    print(recall("status"))


main()
